# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: span.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'span.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nspan.proto\x12\rinfertrace.v1\"\xb1\x01\n\x04Span\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0f\n\x07span_id\x18\x02 \x01(\t\x12\x14\n\x0cservice_name\x18\x03 \x01(\t\x12\x16\n\x0eoperation_name\x18\x04 \x01(\t\x12\x12\n\nmodel_name\x18\x05 \x01(\t\x12\x1c\n\x14start_time_unix_nano\x18\x06 \x01(\x03\x12\x16\n\x0e\x64uration_nanos\x18\x07 \x01(\x03\x12\x0e\n\x06status\x18\x08 \x01(\t\":\n\x14SendSpanBatchRequest\x12\"\n\x05spans\x18\x01 \x03(\x0b\x32\x13.infertrace.v1.Span\"G\n\x15SendSpanBatchResponse\x12\x16\n\x0e\x61\x63\x63\x65pted_count\x18\x01 \x01(\x05\x12\x16\n\x0erejected_count\x18\x02 \x01(\x05\x32n\n\x10\x43ollectorService\x12Z\n\rSendSpanBatch\x12#.infertrace.v1.SendSpanBatchRequest\x1a$.infertrace.v1.SendSpanBatchResponseB8Z6github.com/danielgraviet/infertrace/proto;infertracepbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'span_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/danielgraviet/infertrace/proto;infertracepb'
  _globals['_SPAN']._serialized_start=30
  _globals['_SPAN']._serialized_end=207
  _globals['_SENDSPANBATCHREQUEST']._serialized_start=209
  _globals['_SENDSPANBATCHREQUEST']._serialized_end=267
  _globals['_SENDSPANBATCHRESPONSE']._serialized_start=269
  _globals['_SENDSPANBATCHRESPONSE']._serialized_end=340
  _globals['_COLLECTORSERVICE']._serialized_start=342
  _globals['_COLLECTORSERVICE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
