# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from infertrace._proto import span_pb2 as span__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in span_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CollectorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendSpanBatch = channel.unary_unary(
                '/infertrace.v1.CollectorService/SendSpanBatch',
                request_serializer=span__pb2.SendSpanBatchRequest.SerializeToString,
                response_deserializer=span__pb2.SendSpanBatchResponse.FromString,
                _registered_method=True)


class CollectorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendSpanBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CollectorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendSpanBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SendSpanBatch,
                    request_deserializer=span__pb2.SendSpanBatchRequest.FromString,
                    response_serializer=span__pb2.SendSpanBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'infertrace.v1.CollectorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('infertrace.v1.CollectorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CollectorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendSpanBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/infertrace.v1.CollectorService/SendSpanBatch',
            span__pb2.SendSpanBatchRequest.SerializeToString,
            span__pb2.SendSpanBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
