# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'image_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_service.proto\x12\nml_service\"<\n\x0f\x43lassifyRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x15\n\rmodel_version\x18\x02 \x01(\t\"5\n\x10\x43lassifyResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x32W\n\x0fImageClassifier\x12\x44\n\x07Predict\x12\x1b.ml_service.ClassifyRequest\x1a\x1c.ml_service.ClassifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLASSIFYREQUEST']._serialized_start=35
  _globals['_CLASSIFYREQUEST']._serialized_end=95
  _globals['_CLASSIFYRESPONSE']._serialized_start=97
  _globals['_CLASSIFYRESPONSE']._serialized_end=150
  _globals['_IMAGECLASSIFIER']._serialized_start=152
  _globals['_IMAGECLASSIFIER']._serialized_end=239
# @@protoc_insertion_point(module_scope)
