// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/span.proto

package infertracepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Span struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TraceId           string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId            string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	ServiceName       string                 `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	OperationName     string                 `protobuf:"bytes,4,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	ModelName         string                 `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	StartTimeUnixNano int64                  `protobuf:"varint,6,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	DurationNanos     int64                  `protobuf:"varint,7,opt,name=duration_nanos,json=durationNanos,proto3" json:"duration_nanos,omitempty"`
	Status            string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_proto_span_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_proto_span_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_proto_span_proto_rawDescGZIP(), []int{0}
}

func (x *Span) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Span) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *Span) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Span) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *Span) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *Span) GetStartTimeUnixNano() int64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *Span) GetDurationNanos() int64 {
	if x != nil {
		return x.DurationNanos
	}
	return 0
}

func (x *Span) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SendSpanBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spans         []*Span                `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSpanBatchRequest) Reset() {
	*x = SendSpanBatchRequest{}
	mi := &file_proto_span_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSpanBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSpanBatchRequest) ProtoMessage() {}

func (x *SendSpanBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_span_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSpanBatchRequest.ProtoReflect.Descriptor instead.
func (*SendSpanBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_span_proto_rawDescGZIP(), []int{1}
}

func (x *SendSpanBatchRequest) GetSpans() []*Span {
	if x != nil {
		return x.Spans
	}
	return nil
}

type SendSpanBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcceptedCount int32                  `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	RejectedCount int32                  `protobuf:"varint,2,opt,name=rejected_count,json=rejectedCount,proto3" json:"rejected_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSpanBatchResponse) Reset() {
	*x = SendSpanBatchResponse{}
	mi := &file_proto_span_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSpanBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSpanBatchResponse) ProtoMessage() {}

func (x *SendSpanBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_span_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSpanBatchResponse.ProtoReflect.Descriptor instead.
func (*SendSpanBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_span_proto_rawDescGZIP(), []int{2}
}

func (x *SendSpanBatchResponse) GetAcceptedCount() int32 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *SendSpanBatchResponse) GetRejectedCount() int32 {
	if x != nil {
		return x.RejectedCount
	}
	return 0
}

var File_proto_span_proto protoreflect.FileDescriptor

const file_proto_span_proto_rawDesc = "" +
	"\n" +
	"\x10proto/span.proto\x12\rinfertrace.v1\"\x93\x02\n" +
	"\x04Span\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12%\n" +
	"\x0eoperation_name\x18\x04 \x01(\tR\roperationName\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\x12/\n" +
	"\x14start_time_unix_nano\x18\x06 \x01(\x03R\x11startTimeUnixNano\x12%\n" +
	"\x0eduration_nanos\x18\a \x01(\x03R\rdurationNanos\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"A\n" +
	"\x14SendSpanBatchRequest\x12)\n" +
	"\x05spans\x18\x01 \x03(\v2\x13.infertrace.v1.SpanR\x05spans\"e\n" +
	"\x15SendSpanBatchResponse\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x05R\racceptedCount\x12%\n" +
	"\x0erejected_count\x18\x02 \x01(\x05R\rrejectedCount2n\n" +
	"\x10CollectorService\x12Z\n" +
	"\rSendSpanBatch\x12#.infertrace.v1.SendSpanBatchRequest\x1a$.infertrace.v1.SendSpanBatchResponseB8Z6github.com/danielgraviet/infertrace/proto;infertracepbb\x06proto3"

var (
	file_proto_span_proto_rawDescOnce sync.Once
	file_proto_span_proto_rawDescData []byte
)

func file_proto_span_proto_rawDescGZIP() []byte {
	file_proto_span_proto_rawDescOnce.Do(func() {
		file_proto_span_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_span_proto_rawDesc), len(file_proto_span_proto_rawDesc)))
	})
	return file_proto_span_proto_rawDescData
}

var file_proto_span_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_span_proto_goTypes = []any{
	(*Span)(nil),                  // 0: infertrace.v1.Span
	(*SendSpanBatchRequest)(nil),  // 1: infertrace.v1.SendSpanBatchRequest
	(*SendSpanBatchResponse)(nil), // 2: infertrace.v1.SendSpanBatchResponse
}
var file_proto_span_proto_depIdxs = []int32{
	0, // 0: infertrace.v1.SendSpanBatchRequest.spans:type_name -> infertrace.v1.Span
	1, // 1: infertrace.v1.CollectorService.SendSpanBatch:input_type -> infertrace.v1.SendSpanBatchRequest
	2, // 2: infertrace.v1.CollectorService.SendSpanBatch:output_type -> infertrace.v1.SendSpanBatchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_span_proto_init() }
func file_proto_span_proto_init() {
	if File_proto_span_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_span_proto_rawDesc), len(file_proto_span_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_span_proto_goTypes,
		DependencyIndexes: file_proto_span_proto_depIdxs,
		MessageInfos:      file_proto_span_proto_msgTypes,
	}.Build()
	File_proto_span_proto = out.File
	file_proto_span_proto_goTypes = nil
	file_proto_span_proto_depIdxs = nil
}
